# Generated by Django 4.2.4 on 2023-08-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharRoom',
            new_name='ChatRoom',
        ),
    ]
